// YouTube Video Notes Extension - MECE Notes Generator
// Redesigned with modern UX/UI patterns, draggable panel, dark mode, and accessibility

(function () {
  "use strict";

  // ==================== CONFIGURATION ====================
  const CONFIG = {
    API_ENDPOINT:
      "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent",
    MODEL: "gemini-2.0-flash",
    STORAGE_KEYS: {
      API_KEY: "gemini_api_key",
      NOTES: "youtube_video_notes",
      PANEL_STATE: "panel_state",
      PANEL_POSITION: "panel_position",
      PANEL_SIZE: "panel_size",
      REPORT_DEPTH: "report_depth",
      INCLUDE_CHAPTERS: "include_chapters",
      MATCH_LANGUAGE: "match_transcript_language",
    },
    PANEL_ID: "ytn-notes-panel",
    RETRY_ATTEMPTS: 3,
    RETRY_DELAY: 2000,
    DEFAULT_WIDTH: 420,
    MIN_WIDTH: 320,
    MAX_WIDTH: 700,
  };

  // ==================== STATE MANAGEMENT ====================
  let state = {
    currentVideoId: null,
    currentVideoTitle: null,
    currentVideoUrl: null,
    transcript: null,
    transcriptPreview: null,
    notesByDepth: { brief: null, detailed: null },
    activeDepth: "brief",
    isGenerating: false,
    isEditing: false,
    isPanelCollapsed: false,
    isDarkMode: false,
    panelPosition: { x: null, y: null },
    panelSize: { width: CONFIG.DEFAULT_WIDTH },
    isDragging: false,
    dragOffset: { x: 0, y: 0 },
    activeDepth: "brief",
    includeChapters: false,
    matchTranscriptLanguage: false,
    videoDuration: null,
    transcriptQuality: 0.9,
    hasChapters: false,
    chapters: [],
    hasTranscript: false,
    autoGenerated: false,
  };

  // ==================== DOM ELEMENTS ====================
  let panelElements = {};

  // ==================== UTILITY FUNCTIONS ====================

  function debounce(func, wait) {
    let timeout;
    return function executedFunction(...args) {
      const later = () => {
        clearTimeout(timeout);
        func(...args);
      };
      clearTimeout(timeout);
      timeout = setTimeout(later, wait);
    };
  }

  function estimateTokens(text) {
    // Rough estimate: 1 token ≈ 4 characters
    return Math.ceil(text.length / 4);
  }

  function estimateCost(inputTokens, outputTokens = 1500) {
    // Gemini 2.0 Flash: $0.10 per 1M input, $0.40 per 1M output
    const inputCost = (inputTokens / 1000000) * 0.1;
    const outputCost = (outputTokens / 1000000) * 0.4;
    return (inputCost + outputCost).toFixed(4);
  }

  function formatDuration(seconds) {
    const hrs = Math.floor(seconds / 3600);
    const mins = Math.floor((seconds % 3600) / 60);
    const secs = seconds % 60;

    if (hrs > 0) {
      return `${hrs}h ${mins}m`;
    } else if (mins > 0) {
      return `${mins}m ${secs}s`;
    } else {
      return `${secs}s`;
    }
  }

  function getNotesForDepth(depth) {
    return state.notesByDepth[depth] || null;
  }

  function hasAnyNotes() {
    return Boolean(state.notesByDepth.brief || state.notesByDepth.detailed);
  }

  function getVideoDurationSeconds() {
    const videoEl = document.querySelector("video");
    if (videoEl && Number.isFinite(videoEl.duration) && videoEl.duration > 0) {
      return Math.floor(videoEl.duration);
    }
    try {
      const player = document.getElementById("movie_player");
      if (player && typeof player.getDuration === "function") {
        const duration = player.getDuration();
        if (Number.isFinite(duration) && duration > 0) {
          return Math.floor(duration);
        }
      }
    } catch (error) {
      console.warn("[YouTube Notes] Unable to read video duration", error);
    }
    return null;
  }

  function getCaptionTrackInfo() {
    try {
      const tracks =
        window.ytInitialPlayerResponse?.captions
          ?.playerCaptionsTracklistRenderer?.captionTracks || [];
      if (tracks.length === 0) return null;
      const defaultTrack = tracks[0];
      return {
        isAutoGenerated: defaultTrack.kind === "asr",
        language: defaultTrack.languageCode,
      };
    } catch (error) {
      return null;
    }
  }

  function detectChapters() {
    const chapterRenderer = document.querySelector(
      "ytd-macro-markers-list-renderer"
    );
    if (!chapterRenderer) return [];
    const chapterItems = Array.from(
      chapterRenderer.querySelectorAll("ytd-macro-markers-list-item-renderer")
    );
    return chapterItems
      .map((item) => {
        const title =
          item.querySelector("#details #title")?.textContent?.trim() ||
          item.querySelector("#title")?.textContent?.trim();
        const time =
          item.querySelector("#time")?.textContent?.trim() ||
          item.querySelector("#timestamp")?.textContent?.trim();
        if (!title) return null;
        return time ? `${time} ${title}` : title;
      })
      .filter(Boolean);
  }

  function hasTranscriptAvailable() {
    return Array.from(document.querySelectorAll("button")).some((btn) =>
      ["Show transcript", "Open transcript"].some((label) =>
        btn.textContent.includes(label)
      )
    );
  }

  // ==================== THEME DETECTION ====================

  function detectDarkMode() {
    const htmlElement = document.documentElement;
    const isDark =
      htmlElement.getAttribute("dark") === "true" ||
      htmlElement.hasAttribute("dark");
    state.isDarkMode = isDark;
    return isDark;
  }

  function updateTheme() {
    const isDark = detectDarkMode();
    const panel = document.getElementById(CONFIG.PANEL_ID);
    if (panel) {
      panel.classList.toggle("ytn-dark-mode", isDark);
    }
  }

  // Observe theme changes
  const themeObserver = new MutationObserver(() => {
    updateTheme();
  });

  // ==================== KEYBOARD SHORTCUTS ====================

  function initKeyboardShortcuts() {
    document.addEventListener("keydown", (e) => {
      // Ignore if typing in input/textarea
      if (e.target.matches("input, textarea")) return;

      const isMac = navigator.platform.toUpperCase().indexOf("MAC") >= 0;
      const modKey = isMac ? e.metaKey : e.ctrlKey;

      // Ctrl/Cmd + K - Toggle panel
      if (modKey && e.key === "k") {
        e.preventDefault();
        togglePanel();
      }

      // Ctrl/Cmd + G - Generate notes
      if (modKey && e.key === "g") {
        e.preventDefault();
        if (!state.isGenerating) {
          handleGenerate();
        }
      }

      // Ctrl/Cmd + E - Edit mode
      if (modKey && e.key === "e") {
        e.preventDefault();
        if (hasAnyNotes() && !state.isEditing) {
          handleEdit();
        }
      }

      // ESC - Close panel or cancel edit
      if (e.key === "Escape") {
        if (state.isEditing) {
          cancelEdit();
        } else {
          togglePanel(false);
        }
      }
    });
  }

  // ==================== TOAST NOTIFICATIONS ====================

  function showToast(message, type = "info", duration = 3000) {
    const existingToast = document.querySelector(".ytn-toast");
    if (existingToast) {
      existingToast.remove();
    }

    const toast = document.createElement("div");
    toast.className = `ytn-toast ytn-toast-${type}`;
    toast.textContent = message;

    document.body.appendChild(toast);

    // Trigger animation
    setTimeout(() => toast.classList.add("ytn-toast-show"), 10);

    // Auto-remove
    setTimeout(() => {
      toast.classList.remove("ytn-toast-show");
      setTimeout(() => toast.remove(), 300);
    }, duration);
  }

  // ==================== TRANSCRIPT EXTRACTION ====================

  async function extractTranscript() {
    try {
      const urlParams = new URLSearchParams(window.location.search);
      const videoId = urlParams.get("v");

      if (!videoId) {
        throw new Error("Could not extract video ID from URL");
      }

      state.currentVideoId = videoId;
      state.currentVideoUrl = window.location.href;
      state.currentVideoTitle = document.title.replace(" - YouTube", "");

      const transcriptData = await getTranscriptFromYouTube();

      if (!transcriptData || transcriptData.length === 0) {
        throw new Error("No transcript available for this video");
      }

      const fullTranscript = transcriptData
        .map((segment) => segment.text)
        .join(" ");

      state.transcript = fullTranscript;
      state.transcriptPreview = fullTranscript.substring(0, 500) + "...";
      state.hasTranscript = true;

      console.log(
        `[YouTube Notes] Extracted ${fullTranscript.length} characters of transcript`
      );
      return fullTranscript;
    } catch (error) {
      console.error("[YouTube Notes] Transcript extraction error:", error);
      throw error;
    }
  }

  async function getTranscriptFromYouTube() {
    return new Promise((resolve, reject) => {
      const transcriptButton = Array.from(
        document.querySelectorAll("button")
      ).find(
        (btn) =>
          btn.textContent.includes("Show transcript") ||
          btn.textContent.includes("Open transcript") ||
          btn.textContent.includes("Показать текст видео")
      );

      if (!transcriptButton) {
        reject(new Error("Transcript button not found"));
        return;
      }

      transcriptButton.click();

      setTimeout(() => {
        try {
          const transcriptSegments = document.querySelectorAll(
            "#segments-container ytd-transcript-segment-renderer"
          );
          const transcriptData = [];

          transcriptSegments.forEach((segment) => {
            const textElement = segment.querySelector(".segment-text");
            if (textElement) {
              transcriptData.push({
                text: textElement.textContent.trim(),
              });
            }
          });

          const closeButton = document.querySelector(
            "#top-level-buttons-computed ytd-button-renderer"
          );
          if (closeButton) {
            closeButton.click();
          }

          if (transcriptData.length > 0) {
            resolve(transcriptData);
          } else {
            reject(new Error("No transcript segments found"));
          }
        } catch (error) {
          reject(error);
        }
      }, 2000);
    });
  }

  // ==================== API INTEGRATION ====================

  async function generateNotes(transcript, depth) {
    const apiKey = await getApiKey();

    if (!apiKey) {
      throw new Error("API key not configured");
    }

    const depthInstruction =
      depth === "detailed"
        ? `Depth: Detailed. Expand analysis and include more nuance and examples. Use longer paragraphs when helpful and include more supporting bullets per section (up to 6).`
        : `Depth: Brief. Keep it concise and high-level. Prefer short paragraphs and keep bullets to a minimum (up to 3 per section).`;

    const languageInstruction = state.matchTranscriptLanguage
      ? "IMPORTANT: Write the report only in the same language as the transcript. Do not use English unless the transcript is English. If the transcript is mixed, use the dominant language."
      : "IMPORTANT: Write the report only in English.";

    const chapterInstruction =
      state.includeChapters && state.chapters?.length
        ? `Include the following chapter markers where relevant:\n${state.chapters
            .map((chapter) => `- ${chapter}`)
            .join("\n")}`
        : state.includeChapters
        ? "If chapters are available, include chapter markers in section headings."
        : "Do not include chapter markers unless explicitly provided.";

    const systemPrompt = `You are an expert at creating McKinsey-style MECE (Mutually Exclusive, Collectively Exhaustive) reports from video transcripts.

Your task is to transform video transcripts into highly structured, executive-level notes that:

1. **Structure**: Use clear hierarchical organization with main themes and supporting points
2. **MECE Framework**: Ensure all key points are covered without overlap or redundancy
3. **High Signal**: Remove all fluff, filler words, and non-essential content
4. **Actionability**: Highlight key insights, frameworks, and takeaways
5. **Clarity**: Use precise, professional language with concrete examples

**CRITICAL MARKDOWN FORMATTING RULES:**
- Use hyphens (-) for ALL bullet points, NEVER asterisks (*)
- Use ## for main sections, ### for subsections
- Headings must be plain headings (e.g., "## Executive Summary"), not list items
- Prefer paragraphs; use lists only for concise supporting points
- Keep formatting clean and consistent

${depthInstruction}
${languageInstruction}
${chapterInstruction}

Format your response in Markdown as a report:
- ## Executive Summary: Short paragraph. Optional short bullet list.
- ## Key Themes: 2-5 subsections with paragraphs and optional bullets.
- ## Critical Insights: A brief lead-in sentence plus bullets.
- ## Notable Quotes: Only if there are strong direct quotes; use bullets.
- ## Recommendations: If applicable; use bullets.

Focus on signal over noise. Every word should add value. Be ruthless in removing redundancy.`;

    const userPrompt = `Please generate McKinsey-style MECE notes from the following YouTube video transcript:\n\n${transcript}\n\nVideo Title: ${state.currentVideoTitle}\nVideo URL: ${state.currentVideoUrl}\n\nLanguage requirement: ${
      state.matchTranscriptLanguage
        ? "Match the transcript language exactly."
        : "English only."
    }`;

    try {
      const response = await fetch(`${CONFIG.API_ENDPOINT}?key=${apiKey}`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          contents: [
            {
              parts: [
                {
                  text: `${systemPrompt}\n\n${userPrompt}`,
                },
              ],
            },
          ],
          generationConfig: {
            temperature: 0.7,
            maxOutputTokens: 2048,
          },
        }),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => null);
        console.error("[YouTube Notes] API Error Details:", {
          status: response.status,
          statusText: response.statusText,
          errorData: errorData,
          modelUsed: CONFIG.MODEL,
        });
        const error = new Error(
          `API error: ${response.status} - ${
            errorData?.error?.message || response.statusText
          }`
        );
        error.status = response.status;
        error.apiMessage = errorData?.error?.message || response.statusText;
        throw error;
      }

      const data = await response.json();
      const notes = data.candidates[0].content.parts[0].text;
      return notes;
    } catch (error) {
      console.error("[YouTube Notes] API error:", error);
      throw error;
    }
  }

  // ==================== STORAGE MANAGEMENT ====================

  async function getApiKey() {
    return new Promise((resolve) => {
      chrome.storage.local.get([CONFIG.STORAGE_KEYS.API_KEY], (result) => {
        resolve(result[CONFIG.STORAGE_KEYS.API_KEY] || null);
      });
    });
  }

  async function saveApiKey(apiKey) {
    return new Promise((resolve) => {
      chrome.storage.local.set(
        {
          [CONFIG.STORAGE_KEYS.API_KEY]: apiKey,
        },
        resolve
      );
    });
  }

  async function saveNotes(videoId, overrides = {}) {
    return new Promise((resolve) => {
      chrome.storage.local.get([CONFIG.STORAGE_KEYS.NOTES], (result) => {
        const allNotes = result[CONFIG.STORAGE_KEYS.NOTES] || {};
        const notesBrief =
          overrides.brief !== undefined
            ? overrides.brief
            : state.notesByDepth.brief;
        const notesDetailed =
          overrides.detailed !== undefined
            ? overrides.detailed
            : state.notesByDepth.detailed;
        const activeDepth =
          overrides.activeDepth || state.activeDepth || "brief";

        allNotes[videoId] = {
          notes: notesBrief || notesDetailed || "",
          notesBrief: notesBrief || "",
          notesDetailed: notesDetailed || "",
          title: state.currentVideoTitle,
          url: state.currentVideoUrl,
          videoId: videoId,
          activeDepth,
          createdAt: allNotes[videoId]?.createdAt || new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        };

        chrome.storage.local.set(
          {
            [CONFIG.STORAGE_KEYS.NOTES]: allNotes,
          },
          resolve
        );
      });
    });
  }

  async function loadUserSettings() {
    return new Promise((resolve) => {
      chrome.storage.local.get(
        [
          CONFIG.STORAGE_KEYS.REPORT_DEPTH,
          CONFIG.STORAGE_KEYS.INCLUDE_CHAPTERS,
          CONFIG.STORAGE_KEYS.MATCH_LANGUAGE,
        ],
        (result) => {
          const reportDepth = result[CONFIG.STORAGE_KEYS.REPORT_DEPTH];
          const includeChapters = result[CONFIG.STORAGE_KEYS.INCLUDE_CHAPTERS];
          const matchLanguage = result[CONFIG.STORAGE_KEYS.MATCH_LANGUAGE];
          if (reportDepth === "brief" || reportDepth === "detailed") {
            state.activeDepth = reportDepth;
          }
          if (typeof includeChapters === "boolean") {
            state.includeChapters = includeChapters;
          }
          if (typeof matchLanguage === "boolean") {
            state.matchTranscriptLanguage = matchLanguage;
          }
          resolve();
        }
      );
    });
  }

  async function saveUserSettings() {
    return new Promise((resolve) => {
      chrome.storage.local.set(
        {
          [CONFIG.STORAGE_KEYS.REPORT_DEPTH]: state.activeDepth,
          [CONFIG.STORAGE_KEYS.INCLUDE_CHAPTERS]: state.includeChapters,
          [CONFIG.STORAGE_KEYS.MATCH_LANGUAGE]:
            state.matchTranscriptLanguage,
        },
        resolve
      );
    });
  }

  async function loadNotes(videoId) {
    return new Promise((resolve) => {
      chrome.storage.local.get([CONFIG.STORAGE_KEYS.NOTES], (result) => {
        const allNotes = result[CONFIG.STORAGE_KEYS.NOTES] || {};
        resolve(allNotes[videoId] || null);
      });
    });
  }

  async function savePanelState() {
    return new Promise((resolve) => {
      chrome.storage.local.set(
        {
          [CONFIG.STORAGE_KEYS.PANEL_STATE]: {
            collapsed: state.isPanelCollapsed,
            position: state.panelPosition,
            size: state.panelSize,
          },
        },
        resolve
      );
    });
  }

  async function loadPanelState() {
    return new Promise((resolve) => {
      chrome.storage.local.get([CONFIG.STORAGE_KEYS.PANEL_STATE], (result) => {
        const panelState = result[CONFIG.STORAGE_KEYS.PANEL_STATE] || {};
        if (panelState.position) {
          state.panelPosition = panelState.position;
        }
        if (panelState.size) {
          state.panelSize = panelState.size;
        }
        state.isPanelCollapsed = panelState.collapsed || false;
        resolve(panelState);
      });
    });
  }

  // ==================== TOOLBAR BUTTON ====================

  function createToolbarButton() {
    // Remove existing button
    const existingBtn = document.getElementById("ytn-toolbar-btn");
    if (existingBtn) {
      existingBtn.remove();
    }

    // Find YouTube's top bar (right side controls)
    const topBar = document.querySelector("#end");
    if (!topBar) {
      console.warn("[YouTube Notes] Could not find YouTube toolbar");
      return;
    }

    const toolbarBtn = document.createElement("button");
    toolbarBtn.id = "ytn-toolbar-btn";
    toolbarBtn.className = "ytn-toolbar-button";
    toolbarBtn.title = "Notes (Ctrl+K)";
    toolbarBtn.innerHTML = `
      <svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">
        <path d="M14,2H6A2,2 0 0,0 4,4V20A2,2 0 0,0 6,22H18A2,2 0 0,0 20,20V8L14,2M18,20H6V4H13V9H18V20Z"/>
      </svg>
    `;

    toolbarBtn.addEventListener("click", () => togglePanel());

    // Insert before the first child of the top bar
    topBar.insertBefore(toolbarBtn, topBar.firstChild);
  }

  // ==================== UI CREATION ====================

  function createPanel() {
    const existingPanel = document.getElementById(CONFIG.PANEL_ID);
    if (existingPanel) {
      existingPanel.remove();
    }

    detectDarkMode();

    const panel = document.createElement("div");
    panel.id = CONFIG.PANEL_ID;
    panel.className = state.isDarkMode ? "ytn-dark-mode" : "";

    // Apply saved size
    if (state.panelSize.width) {
      panel.style.width = state.panelSize.width + "px";
    }

    panel.innerHTML = `
      <style>
        /* ==================== VARIABLES ==================== */
        #${CONFIG.PANEL_ID} {
          /* Light mode colors */
          --ytn-bg-primary: #FFFFFF;
          --ytn-bg-secondary: #F9F9F9;
          --ytn-bg-tertiary: #F1F1F1;
          --ytn-text-primary: #0F0F0F;
          --ytn-text-secondary: #606060;
          --ytn-text-tertiary: #909090;
          --ytn-border: #E5E5E5;
          --ytn-border-hover: #CCCCCC;
          --ytn-accent: #FF0000;
          --ytn-accent-hover: #CC0000;
          --ytn-success: #00D924;
          --ytn-warning: #FF9800;
          --ytn-error: #F44336;
          --ytn-shadow: rgba(0, 0, 0, 0.1);
          --ytn-shadow-lg: rgba(0, 0, 0, 0.15);
          
          /* Spacing */
          --space-1: 4px;
          --space-2: 8px;
          --space-3: 12px;
          --space-4: 16px;
          --space-6: 24px;
          --space-8: 32px;
          
          /* Typography */
          --text-xs: 11px;
          --text-sm: 13px;
          --text-base: 14px;
          --text-lg: 16px;
          --text-xl: 20px;
          
          /* Transitions */
          --transition-fast: 150ms ease;
          --transition-base: 250ms ease;
          --transition-slow: 350ms ease;
        }

        #${CONFIG.PANEL_ID}.ytn-dark-mode {
          --ytn-bg-primary: #0F0F0F;
          --ytn-bg-secondary: #1F1F1F;
          --ytn-bg-tertiary: #272727;
          --ytn-text-primary: #FFFFFF;
          --ytn-text-secondary: #AAAAAA;
          --ytn-text-tertiary: #717171;
          --ytn-border: #303030;
          --ytn-border-hover: #404040;
          --ytn-shadow: rgba(0, 0, 0, 0.3);
          --ytn-shadow-lg: rgba(0, 0, 0, 0.5);
        }

        /* ==================== TOOLBAR BUTTON ==================== */
        .ytn-toolbar-button {
          display: inline-flex;
          align-items: center;
          justify-content: center;
          width: 40px;
          height: 40px;
          padding: 0;
          margin-right: 8px;
          background: #262626;
          border: none;
          border-radius: 50%;
          cursor: pointer;
          color: #fafafa;
          transition: background var(--transition-fast);
        }

        .ytn-toolbar-button:hover {
          background: #2f2f2f;
        }

        .ytn-dark-mode .ytn-toolbar-button:hover {
          background: #2f2f2f;
        }

        .ytn-toolbar-button svg {
          stroke: currentColor;
        }

        /* ==================== PANEL BASE ==================== */
        #${CONFIG.PANEL_ID} {
          position: fixed;
          top: 56px;
          right: 0;
          width: ${CONFIG.DEFAULT_WIDTH}px;
          height: calc(100vh - 56px);
          background: var(--ytn-bg-primary);
          border-left: 1px solid var(--ytn-border);
          box-shadow: -4px 0 24px var(--ytn-shadow-lg);
          font-family: Roboto, Arial, sans-serif;
          font-size: var(--text-base);
          color: var(--ytn-text-primary);
          z-index: 999999;
          display: flex;
          flex-direction: column;
          overflow: hidden;
          transition: transform var(--transition-base),
                      opacity var(--transition-base);
        }

        #${CONFIG.PANEL_ID}.ytn-hidden {
          transform: translateX(100%);
          pointer-events: none;
        }

        /* ==================== HEADER ==================== */
        .ytn-panel-header {
          display: flex;
          align-items: center;
          justify-content: space-between;
          padding: var(--space-4);
          border-bottom: 1px solid var(--ytn-border);
          user-select: none;
          background: var(--ytn-bg-primary);
        }

        .ytn-panel-title {
          display: flex;
          align-items: center;
          gap: var(--space-2);
          font-size: var(--text-lg);
          font-weight: 500;
          color: var(--ytn-text-primary);
        }

        .ytn-icon-notes {
          width: 20px;
          height: 20px;
          fill: var(--ytn-accent);
        }

        .ytn-video-title {
          font-size: var(--text-xs);
          color: var(--ytn-text-secondary);
          margin-top: 2px;
          white-space: nowrap;
          overflow: hidden;
          text-overflow: ellipsis;
          max-width: 250px;
        }

        .ytn-header-controls {
          display: flex;
          gap: var(--space-1);
        }

        .ytn-header-btn {
          width: 32px;
          height: 32px;
          padding: 0;
          background: transparent;
          border: none;
          border-radius: 6px;
          cursor: pointer;
          display: flex;
          align-items: center;
          justify-content: center;
          color: var(--ytn-text-secondary);
          transition: all var(--transition-fast);
        }

        .ytn-header-btn:hover {
          background: var(--ytn-bg-secondary);
          color: var(--ytn-text-primary);
        }

        .ytn-header-btn svg {
          width: 18px;
          height: 18px;
        }

        /* ==================== BODY ==================== */
        .ytn-panel-body {
          flex: 1;
          overflow-y: auto;
          padding: var(--space-4);
        }

        .ytn-panel-body::-webkit-scrollbar {
          width: 8px;
        }

        .ytn-panel-body::-webkit-scrollbar-track {
          background: var(--ytn-bg-secondary);
        }

        .ytn-panel-body::-webkit-scrollbar-thumb {
          background: var(--ytn-border);
          border-radius: 4px;
        }

        .ytn-panel-body::-webkit-scrollbar-thumb:hover {
          background: var(--ytn-border-hover);
        }

        /* ==================== EMPTY STATE ==================== */
        .ytn-empty-state {
          text-align: center;
          padding: var(--space-8) var(--space-4);
        }

        .ytn-empty-icon {
          width: 64px;
          height: 64px;
          margin: 0 auto var(--space-4);
          opacity: 0.3;
        }

        .ytn-empty-title {
          font-size: var(--text-xl);
          font-weight: 500;
          margin-bottom: var(--space-2);
          color: var(--ytn-text-primary);
        }

        .ytn-empty-description {
          font-size: var(--text-sm);
          color: var(--ytn-text-secondary);
          margin-bottom: var(--space-6);
          line-height: 1.5;
        }

        .ytn-onboarding {
          margin: var(--space-4) auto 0;
          padding: var(--space-4);
          border-radius: 8px;
          background: var(--ytn-bg-secondary);
          border: 1px solid var(--ytn-border);
          text-align: left;
          max-width: 320px;
        }

        .ytn-onboarding-title {
          font-size: var(--text-sm);
          font-weight: 600;
          color: var(--ytn-text-primary);
          margin-bottom: var(--space-2);
        }

        .ytn-onboarding-steps {
          padding-left: var(--space-4);
          margin-bottom: var(--space-3);
          color: var(--ytn-text-secondary);
          font-size: var(--text-sm);
        }

        .ytn-onboarding-steps li {
          margin-bottom: var(--space-1);
        }

        /* ==================== TRANSCRIPT PREVIEW ==================== */
        .ytn-transcript-preview {
          background: var(--ytn-bg-secondary);
          border: 1px solid var(--ytn-border);
          border-radius: 8px;
          padding: var(--space-3);
          margin-bottom: var(--space-4);
        }

        .ytn-transcript-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: var(--space-2);
        }

        .ytn-transcript-label {
          font-size: var(--text-xs);
          font-weight: 600;
          text-transform: uppercase;
          letter-spacing: 0.5px;
          color: var(--ytn-text-secondary);
        }

        .ytn-transcript-stats {
          font-size: var(--text-xs);
          color: var(--ytn-text-tertiary);
        }

        .ytn-transcript-content {
          font-size: var(--text-sm);
          line-height: 1.6;
          color: var(--ytn-text-secondary);
          max-height: 100px;
          overflow: hidden;
          position: relative;
        }

        .ytn-transcript-content::after {
          content: '';
          position: absolute;
          bottom: 0;
          left: 0;
          right: 0;
          height: 30px;
          background: linear-gradient(transparent, var(--ytn-bg-secondary));
        }

        .ytn-transcript-hints {
          margin-top: var(--space-3);
          display: grid;
          gap: var(--space-2);
          font-size: var(--text-xs);
          color: var(--ytn-text-secondary);
        }

        .ytn-transcript-hint {
          padding: var(--space-2);
          border-radius: 6px;
          background: var(--ytn-bg-primary);
          border: 1px solid var(--ytn-border);
        }

        /* ==================== PROGRESS ==================== */
        .ytn-progress-container {
          margin-bottom: var(--space-4);
        }

        .ytn-progress-steps {
          display: flex;
          align-items: center;
          gap: var(--space-2);
          margin-bottom: var(--space-3);
        }

        .ytn-progress-step {
          flex: 1;
          height: 4px;
          background: var(--ytn-bg-tertiary);
          border-radius: 2px;
          overflow: hidden;
          position: relative;
        }

        .ytn-progress-step.active {
          background: var(--ytn-accent);
        }

        .ytn-progress-step.active::after {
          content: '';
          position: absolute;
          left: 0;
          top: 0;
          bottom: 0;
          width: 0;
          background: linear-gradient(90deg, transparent, rgba(255,255,255,0.3));
          animation: ytn-progress-shimmer 1.5s infinite;
        }

        @keyframes ytn-progress-shimmer {
          0% { width: 0; }
          100% { width: 100%; }
        }

        .ytn-progress-text {
          font-size: var(--text-sm);
          color: var(--ytn-text-secondary);
          display: flex;
          align-items: center;
          gap: var(--space-2);
        }

        .ytn-error-panel {
          border: 1px solid var(--ytn-border);
          border-left: 4px solid var(--ytn-error);
          background: var(--ytn-bg-secondary);
          border-radius: 10px;
          padding: var(--space-4);
          display: grid;
          gap: var(--space-2);
        }

        .ytn-error-title {
          font-size: var(--text-sm);
          font-weight: 600;
          color: var(--ytn-text-primary);
        }

        .ytn-error-detail {
          font-size: var(--text-xs);
          color: var(--ytn-text-secondary);
          line-height: 1.5;
        }

        .ytn-spinner {
          width: 14px;
          height: 14px;
          border: 2px solid var(--ytn-border);
          border-top-color: var(--ytn-accent);
          border-radius: 50%;
          animation: ytn-spin 0.8s linear infinite;
        }

        @keyframes ytn-spin {
          to { transform: rotate(360deg); }
        }

        /* ==================== NOTES DISPLAY ==================== */
        .ytn-notes-content {
          line-height: 1.6;
        }

        .ytn-notes-content h1,
        .ytn-notes-content h2,
        .ytn-notes-content h3 {
          color: var(--ytn-text-primary);
          margin-top: var(--space-4);
          margin-bottom: var(--space-3);
          font-weight: 600;
        }

        .ytn-notes-content h1 {
          font-size: var(--text-xl);
          padding-bottom: var(--space-2);
          border-bottom: 2px solid var(--ytn-border);
        }

        .ytn-notes-content h2 {
          font-size: var(--text-lg);
        }

        .ytn-notes-content h3 {
          font-size: var(--text-base);
        }

        .ytn-notes-content p {
          margin-bottom: var(--space-3);
          color: var(--ytn-text-primary);
        }

        .ytn-notes-content ul,
        .ytn-notes-content ol {
          margin: var(--space-3) 0;
          padding-left: var(--space-6);
        }

        .ytn-notes-content li {
          margin-bottom: var(--space-2);
          color: var(--ytn-text-primary);
        }

        .ytn-notes-content strong {
          color: var(--ytn-text-primary);
          font-weight: 600;
        }

        .ytn-notes-content em {
          font-style: italic;
          color: var(--ytn-text-secondary);
        }

        .ytn-notes-content blockquote {
          border-left: 3px solid var(--ytn-accent);
          padding-left: var(--space-4);
          margin: var(--space-4) 0;
          color: var(--ytn-text-secondary);
          font-style: italic;
        }

        .ytn-notes-content table {
          width: 100%;
          border-collapse: collapse;
          margin: var(--space-4) 0;
          font-size: var(--text-sm);
        }

        .ytn-notes-content th,
        .ytn-notes-content td {
          border: 1px solid var(--ytn-border);
          padding: 8px 10px;
          text-align: left;
        }

        .ytn-notes-content th {
          background: var(--ytn-bg-secondary);
          font-weight: 600;
        }

        .ytn-notes-content code {
          background: var(--ytn-bg-secondary);
          padding: 2px 6px;
          border-radius: 4px;
          font-family: 'Courier New', monospace;
          font-size: var(--text-sm);
        }

        /* ==================== NOTES EDITOR ==================== */
        .ytn-notes-editor {
          width: 100%;
          min-height: 300px;
          padding: var(--space-4);
          border: 1px solid var(--ytn-border);
          border-radius: 8px;
          background: var(--ytn-bg-secondary);
          color: var(--ytn-text-primary);
          font-family: 'Courier New', monospace;
          font-size: var(--text-sm);
          line-height: 1.6;
          resize: vertical;
          display: none;
        }

        .ytn-notes-editor:focus {
          outline: none;
          border-color: var(--ytn-accent);
          box-shadow: 0 0 0 3px rgba(255, 0, 0, 0.1);
        }

        /* ==================== FOOTER ==================== */
        .ytn-panel-footer {
          padding: var(--space-4);
          border-top: 1px solid var(--ytn-border);
          background: var(--ytn-bg-primary);
        }

        .ytn-actions {
          display: flex;
          gap: var(--space-2);
          margin-bottom: var(--space-3);
          padding-top: var(--space-3);
        }

        .ytn-settings-row {
          display: flex;
          align-items: center;
          justify-content: space-between;
          gap: var(--space-3);
          flex-wrap: wrap;
          margin-bottom: var(--space-3);
        }

        .ytn-settings-left,
        .ytn-settings-right {
          display: flex;
          align-items: center;
          gap: var(--space-3);
          flex-wrap: wrap;
        }

        .ytn-settings-right {
          margin-left: auto;
        }

        .ytn-setting {
          display: inline-flex;
          align-items: center;
          gap: var(--space-2);
          color: var(--ytn-text-secondary);
          font-size: var(--text-xs);
        }

        .ytn-settings-help {
          font-size: var(--text-xs);
          color: var(--ytn-text-tertiary);
          line-height: 1.5;
          margin-bottom: var(--space-3);
        }

        .ytn-setting input[type="checkbox"] {
          width: 14px;
          height: 14px;
          accent-color: var(--ytn-accent);
        }

        .ytn-actions-secondary {
          display: flex;
          gap: var(--space-2);
          justify-content: flex-end;
          margin-bottom: var(--space-2);
        }

        .ytn-btn-select {
          appearance: none;
          padding: var(--space-2) var(--space-4);
          border-radius: 6px;
          border: 1px solid var(--ytn-border);
          background: var(--ytn-bg-secondary);
          color: var(--ytn-text-primary);
          font-size: var(--text-sm);
          font-weight: 500;
          cursor: pointer;
        }

        .ytn-view-all-btn {
          margin: var(--space-3) auto 0;
          padding: var(--space-2) var(--space-3);
          background: transparent;
          border: 1px solid var(--ytn-border);
          color: var(--ytn-text-secondary);
          font-size: var(--text-sm);
          text-align: center;
          cursor: pointer;
          transition: all var(--transition-fast);
          border-radius: 6px;
          display: inline-flex;
          align-items: center;
          justify-content: center;
          gap: var(--space-2);
        }

        .ytn-view-all-btn:hover {
          background: var(--ytn-bg-secondary);
          border-color: var(--ytn-border-hover);
          color: var(--ytn-text-primary);
        }

        .ytn-view-all-btn svg {
          width: 16px;
          height: 16px;
        }

        /* ==================== BUTTONS ==================== */
        .ytn-btn {
          padding: var(--space-2) var(--space-4);
          border: none;
          border-radius: 6px;
          font-size: var(--text-sm);
          font-weight: 500;
          cursor: pointer;
          transition: all var(--transition-fast);
          display: inline-flex;
          align-items: center;
          justify-content: center;
          gap: var(--space-2);
          white-space: nowrap;
        }

        .ytn-btn:disabled {
          opacity: 0.5;
          cursor: not-allowed;
        }

        .ytn-btn-primary {
          flex: 1;
          background: var(--ytn-accent);
          color: white;
          font-weight: 600;
          padding: var(--space-3) var(--space-4);
        }

        .ytn-btn-primary:hover:not(:disabled) {
          background: var(--ytn-accent-hover);
          transform: translateY(-1px);
          box-shadow: 0 4px 12px rgba(255, 0, 0, 0.2);
        }

        .ytn-btn-primary:active:not(:disabled) {
          transform: translateY(0);
        }

        .ytn-btn-secondary {
          background: var(--ytn-bg-secondary);
          color: var(--ytn-text-primary);
          border: 1px solid var(--ytn-border);
        }

        .ytn-btn-secondary:hover:not(:disabled) {
          background: var(--ytn-bg-tertiary);
          border-color: var(--ytn-border-hover);
        }

        .ytn-btn-ghost {
          background: transparent;
          color: var(--ytn-text-secondary);
          padding: var(--space-2);
        }

        .ytn-btn-ghost:hover:not(:disabled) {
          background: var(--ytn-bg-secondary);
          color: var(--ytn-text-primary);
        }

        .ytn-btn svg {
          width: 16px;
          height: 16px;
        }

        /* ==================== COST ESTIMATE ==================== */
        .ytn-cost-estimate {
          font-size: var(--text-xs);
          color: var(--ytn-text-tertiary);
          text-align: center;
          margin-top: var(--space-2);
        }

        .ytn-cost-estimate strong {
          color: var(--ytn-success);
          font-weight: 600;
        }

        /* ==================== TOAST NOTIFICATIONS ==================== */
        .ytn-toast {
          position: fixed;
          top: 20px;
          right: 20px;
          background: var(--ytn-bg-primary);
          border: 1px solid var(--ytn-border);
          border-left: 4px solid var(--ytn-accent);
          padding: var(--space-4);
          border-radius: 8px;
          box-shadow: 0 8px 24px var(--ytn-shadow-lg);
          font-size: var(--text-sm);
          max-width: 300px;
          z-index: 9999999;
          transform: translateX(400px);
          opacity: 0;
          transition: all var(--transition-base);
        }

        .ytn-toast.ytn-toast-show {
          transform: translateX(0);
          opacity: 1;
        }

        .ytn-toast.ytn-toast-success {
          border-left-color: var(--ytn-success);
        }

        .ytn-toast.ytn-toast-error {
          border-left-color: var(--ytn-error);
        }

        .ytn-toast.ytn-toast-warning {
          border-left-color: var(--ytn-warning);
        }

        /* ==================== KEYBOARD SHORTCUTS HINT ==================== */
        .ytn-keyboard-hint {
          font-size: var(--text-xs);
          color: var(--ytn-text-tertiary);
          text-align: center;
          padding: var(--space-2);
          border-top: 1px solid var(--ytn-border);
        }

        .ytn-kbd {
          display: inline-block;
          padding: 2px 6px;
          background: var(--ytn-bg-secondary);
          border: 1px solid var(--ytn-border);
          border-radius: 4px;
          font-family: monospace;
          font-size: var(--text-xs);
        }

        /* ==================== ANIMATIONS ==================== */
        @keyframes ytn-fade-in {
          from {
            opacity: 0;
            transform: translateY(10px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }

        .ytn-fade-in {
          animation: ytn-fade-in var(--transition-base);
        }
      </style>

      <div class="ytn-panel-header">
        <div>
          <div class="ytn-panel-title">
            <svg class="ytn-icon-notes" viewBox="0 0 24 24">
              <path d="M14,2H6A2,2 0 0,0 4,4V20A2,2 0 0,0 6,22H18A2,2 0 0,0 20,20V8L14,2M18,20H6V4H13V9H18V20Z"/>
            </svg>
            Notes
          </div>
          <div class="ytn-video-title" title="${
            state.currentVideoTitle || "YouTube Video"
          }">${state.currentVideoTitle || "YouTube Video"}</div>
        </div>
        <div class="ytn-header-controls">
          <button class="ytn-header-btn ytn-minimize-btn" title="Minimize to toolbar (Ctrl+K)" aria-label="Minimize panel">
            <svg viewBox="0 0 24 24" fill="currentColor">
              <path d="M19,13H5V11H19V13Z"/>
            </svg>
          </button>
        </div>
      </div>

      <div class="ytn-panel-body">
        <div id="ytn-content-area">
          <div class="ytn-empty-state">
            <svg class="ytn-empty-icon" viewBox="0 0 24 24" fill="currentColor" opacity="0.3">
              <path d="M14,2H6A2,2 0 0,0 4,4V20A2,2 0 0,0 6,22H18A2,2 0 0,0 20,20V8L14,2M18,20H6V4H13V9H18V20Z"/>
            </svg>
            <div class="ytn-empty-title">Generate MECE Notes</div>
          <div class="ytn-empty-description">
            Professional McKinsey-style summaries in seconds
          </div>
          <div class="ytn-onboarding" id="ytn-onboarding" style="display: none;">
            <div class="ytn-onboarding-title">Getting started</div>
            <ol class="ytn-onboarding-steps">
              <li>Click Generate Notes.</li>
              <li>Skim the executive summary.</li>
              <li>Copy or edit the report.</li>
            </ol>
            <button id="ytn-onboarding-dismiss" class="ytn-btn ytn-btn-secondary">
              Got it
            </button>
          </div>
        </div>
        </div>

        <div id="ytn-transcript-preview" style="display: none;"></div>
        <div id="ytn-progress-area" style="display: none;"></div>
        <div id="ytn-notes-content" class="ytn-notes-content" style="display: none;"></div>
        <textarea id="ytn-notes-editor" class="ytn-notes-editor" aria-label="Notes editor"></textarea>
      </div>

      <div class="ytn-panel-footer">
        <div class="ytn-actions">
          <button id="ytn-generate-btn" class="ytn-btn ytn-btn-primary">
            Generate Notes
          </button>
          <button id="ytn-regenerate-btn" class="ytn-btn ytn-btn-secondary" style="display: none;" title="Regenerate notes">
            <svg viewBox="0 0 24 24" fill="currentColor">
              <path d="M17.65,6.35C16.2,4.9 14.21,4 12,4A8,8 0 0,0 4,12A8,8 0 0,0 12,20C15.73,20 18.84,17.45 19.73,14H17.65C16.83,16.33 14.61,18 12,18A6,6 0 0,1 6,12A6,6 0 0,1 12,6C13.66,6 15.14,6.69 16.22,7.78L13,11H20V4L17.65,6.35Z"/>
            </svg>
            Regenerate
          </button>
        </div>

        <div class="ytn-settings-row">
          <div class="ytn-settings-left">
            <label class="ytn-setting" id="ytn-chapters-setting" style="display: none;">
              <input type="checkbox" id="ytn-chapters-toggle" />
              <span>Include chapters</span>
            </label>
            <label class="ytn-setting">
              <input type="checkbox" id="ytn-language-toggle" />
              <span>Match transcript language</span>
            </label>
          </div>
          <div class="ytn-settings-right">
            <select id="ytn-depth-select" class="ytn-btn ytn-btn-secondary ytn-btn-select" aria-label="Report depth">
              <option value="brief">Brief</option>
              <option value="detailed">Detailed</option>
            </select>
          </div>
        </div>
        <div class="ytn-settings-help">
          Match transcript language will generate notes in the same language as the video. Brief generates only a brief report; Detailed generates both brief and detailed.
        </div>

        <div id="ytn-cost-estimate" class="ytn-cost-estimate" style="display: none;"></div>

        <div id="ytn-actions-secondary" class="ytn-actions-secondary">
          <button id="ytn-copy-btn" class="ytn-btn ytn-btn-secondary" title="Copy notes (Ctrl+C)" style="display: none;">
            <svg viewBox="0 0 24 24" fill="currentColor">
              <path d="M19,21H8V7H19M19,5H8A2,2 0 0,0 6,7V21A2,2 0 0,0 8,23H19A2,2 0 0,0 21,21V7A2,2 0 0,0 19,5M16,1H4A2,2 0 0,0 2,3V17H4V3H16V1Z"/>
            </svg>
            Copy
          </button>
          <button id="ytn-download-btn" class="ytn-btn ytn-btn-secondary" title="Download as Markdown" style="display: none;">
            <svg viewBox="0 0 24 24" fill="currentColor">
              <path d="M5,20H19V18H5M19,9H15V3H9V9H5L12,16L19,9Z"/>
            </svg>
            Download
          </button>
          <button id="ytn-edit-btn" class="ytn-btn ytn-btn-secondary" title="Edit notes (Ctrl+E)" style="display: none;">
            <svg viewBox="0 0 24 24" fill="currentColor">
              <path d="M20.71,7.04C21.1,6.65 21.1,6 20.71,5.63L18.37,3.29C18,2.9 17.35,2.9 16.96,3.29L15.12,5.12L18.87,8.87M3,17.25V21H6.75L17.81,9.93L14.06,6.18L3,17.25Z"/>
            </svg>
            Edit
          </button>
        </div>

        <div class="ytn-keyboard-hint">
          <span class="ytn-kbd">Ctrl+K</span> Toggle •
          <span class="ytn-kbd">Ctrl+G</span> Generate •
          <span class="ytn-kbd">ESC</span> Close
        </div>

        <button id="ytn-view-all-btn" class="ytn-view-all-btn">
          <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
            <path d="M3,5H21V7H3V5M3,11H21V13H3V11M3,17H21V19H3V17Z"/>
          </svg>
          View All Notes
        </button>
      </div>
    `;

    document.body.appendChild(panel);

    // Panel is now fixed to right side, no need to apply saved position

    // Cache panel elements
    panelElements = {
      panel: panel,
      contentArea: document.getElementById("ytn-content-area"),
      transcriptPreview: document.getElementById("ytn-transcript-preview"),
      progressArea: document.getElementById("ytn-progress-area"),
      notesContent: document.getElementById("ytn-notes-content"),
      notesEditor: document.getElementById("ytn-notes-editor"),
      onboarding: document.getElementById("ytn-onboarding"),
      onboardingDismiss: document.getElementById("ytn-onboarding-dismiss"),
      generateBtn: document.getElementById("ytn-generate-btn"),
      regenerateBtn: document.getElementById("ytn-regenerate-btn"),
      copyBtn: document.getElementById("ytn-copy-btn"),
      downloadBtn: document.getElementById("ytn-download-btn"),
      editBtn: document.getElementById("ytn-edit-btn"),
      costEstimate: document.getElementById("ytn-cost-estimate"),
      actionsSecondary: document.getElementById("ytn-actions-secondary"),
      minimizeBtn: panel.querySelector(".ytn-minimize-btn"),
      viewAllBtn: document.getElementById("ytn-view-all-btn"),
      depthSelect: document.getElementById("ytn-depth-select"),
      chaptersSetting: document.getElementById("ytn-chapters-setting"),
      chaptersToggle: document.getElementById("ytn-chapters-toggle"),
      languageToggle: document.getElementById("ytn-language-toggle"),
    };

    // Attach event listeners
    panelElements.generateBtn.addEventListener("click", handleGenerate);
    panelElements.regenerateBtn.addEventListener("click", () =>
      handleGenerate(true)
    );
    panelElements.copyBtn.addEventListener("click", handleCopy);
    panelElements.downloadBtn.addEventListener("click", handleDownload);
    panelElements.editBtn.addEventListener("click", handleEdit);
    panelElements.minimizeBtn.addEventListener("click", () =>
      togglePanel(false)
    );
    panelElements.viewAllBtn.addEventListener("click", openNotesLibrary);
    panelElements.depthSelect.addEventListener("change", (event) => {
      state.activeDepth = event.target.value;
      saveUserSettings();
      if (hasAnyNotes()) {
        displayNotesForDepth(state.activeDepth);
      }
    });
    panelElements.chaptersToggle.addEventListener("change", (event) => {
      state.includeChapters = event.target.checked;
      saveUserSettings();
    });
    panelElements.languageToggle.addEventListener("change", (event) => {
      state.matchTranscriptLanguage = event.target.checked;
      saveUserSettings();
    });

    panelElements.depthSelect.value = state.activeDepth;
    panelElements.chaptersToggle.checked = state.includeChapters;
    panelElements.languageToggle.checked = state.matchTranscriptLanguage;
    panelElements.chaptersSetting.style.display = state.hasChapters
      ? "inline-flex"
      : "none";

    const onboardingKey = "ytn_onboarding_seen";
    if (
      panelElements.onboarding &&
      localStorage.getItem(onboardingKey) !== "true"
    ) {
      panelElements.onboarding.style.display = "block";
      panelElements.onboardingDismiss.addEventListener("click", () => {
        panelElements.onboarding.style.display = "none";
        localStorage.setItem(onboardingKey, "true");
      });
    }

    // Make panel draggable (header only, not full drag since it's fixed now)
    // Remove resize functionality since panel is now full height
    // makeDraggable(panel); // Commented out - no longer needed
    // makeResizable(panel); // Commented out - no longer needed

    // Observe theme changes
    themeObserver.observe(document.documentElement, {
      attributes: true,
      attributeFilter: ["dark"],
    });

    return panel;
  }

  async function loadSavedNotes() {
    const videoId = state.currentVideoId;
    if (!videoId) return;

    const savedData = await loadNotes(videoId);
    if (
      savedData &&
      (savedData.notesBrief || savedData.notesDetailed || savedData.notes)
    ) {
      state.notesByDepth.brief =
        savedData.notesBrief || savedData.notes || null;
      state.notesByDepth.detailed = savedData.notesDetailed || null;
      state.activeDepth =
        savedData.activeDepth || savedData.reportDepth || "brief";
      if (panelElements.depthSelect) {
        panelElements.depthSelect.value = state.activeDepth;
      }
      displayNotesForDepth(state.activeDepth);
      showToast("Notes loaded from storage", "info", 2000);
      return true;
    }
    return false;
  }

  // ==================== UI HANDLERS ====================

  function scheduleAutoGenerateIfEligible() {
    const shortVideo =
      state.videoDuration !== null && state.videoDuration < 1800;
    if (!shortVideo || state.autoGenerated) return;
    if (!hasTranscriptAvailable()) return;
    state.autoGenerated = true;
    showToast("Auto-generating notes for short video...", "info", 3000);
    handleGenerate(false, { auto: true });
  }

  async function handleGenerate(regenerate = false, options = {}) {
    if (state.isGenerating) {
      showToast("Generation already in progress...", "info", 2500);
      return;
    }

    try {
      state.isGenerating = true;

      // Check API key
      let apiKey = await getApiKey();
      if (!apiKey) {
        apiKey = await promptForApiKey();
        if (!apiKey) {
          showToast("API key required to generate notes", "error");
          state.isGenerating = false;
          return;
        }
        await saveApiKey(apiKey);
        showToast("API key saved successfully", "success");
      }

      // Hide empty state
      panelElements.contentArea.style.display = "none";

      state.chapters = detectChapters();
      state.hasChapters = state.chapters.length > 0;
      panelElements.chaptersSetting.style.display = state.hasChapters
        ? "inline-flex"
        : "none";

      // Step 1: Extract transcript
      showProgress(1, "Extracting transcript...");
      const transcript = await extractTranscript();

      // Show transcript preview
      showTranscriptPreview(transcript);

      const selectedDepth = state.activeDepth;

      // Step 2: Generate notes
      if (selectedDepth === "detailed" && !state.notesByDepth.brief) {
        showProgress(2, "Generating brief version...");
        const briefNotes = await generateNotes(transcript, "brief");
        state.notesByDepth.brief = briefNotes;
      }

      showProgress(
        2,
        selectedDepth === "detailed"
          ? "Generating detailed version..."
          : state.videoDuration && state.videoDuration > 7200
          ? "Long video detected. Analyzing content..."
          : "Analyzing video content..."
      );

      const notes = await generateNotes(transcript, selectedDepth);
      state.notesByDepth[selectedDepth] = notes;
      state.activeDepth = selectedDepth;

      await saveNotes(state.currentVideoId);

      // Hide progress
      panelElements.progressArea.style.display = "none";

      // Display notes
      displayNotesForDepth(state.activeDepth);

      if (regenerate) {
        showToast("Notes regenerated successfully!", "success");
      } else {
        showToast("Notes generated successfully!", "success");
      }
    } catch (error) {
      console.error("[YouTube Notes] Generation error:", error);
      const friendly = getFriendlyError(error);
      showToast(friendly.toast, friendly.type, 5000);
      if (friendly.type === "error" || friendly.type === "warning") {
        showErrorState(friendly.title, friendly.detail);
      }

      // Show empty state again
      panelElements.contentArea.style.display = "block";
      panelElements.transcriptPreview.style.display = "none";
    } finally {
      state.isGenerating = false;
      updateGenerateButton(false);
    }
  }

  function showProgress(step, message) {
    panelElements.progressArea.style.display = "block";
    panelElements.progressArea.innerHTML = `
      <div class="ytn-progress-container ytn-fade-in">
        <div class="ytn-progress-steps">
          <div class="ytn-progress-step ${step >= 1 ? "active" : ""}"></div>
          <div class="ytn-progress-step ${step >= 2 ? "active" : ""}"></div>
        </div>
        <div class="ytn-progress-text">
          <div class="ytn-spinner"></div>
          ${message}
        </div>
      </div>
    `;
    updateGenerateButton(true);
  }

  function escapeHtmlText(input) {
    return String(input)
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#39;");
  }

  function showErrorState(title, detail) {
    const safeTitle = escapeHtmlText(title);
    const safeDetail = detail ? escapeHtmlText(detail) : "";
    panelElements.progressArea.style.display = "block";
    panelElements.progressArea.innerHTML = `
      <div class="ytn-error-panel ytn-fade-in">
        <div class="ytn-error-title">${safeTitle}</div>
        ${safeDetail ? `<div class="ytn-error-detail">${safeDetail}</div>` : ""}
      </div>
    `;
    updateGenerateButton(false);
  }

  function getFriendlyError(error) {
    const rawMessage = error?.apiMessage || error?.message || "";
    const lowered = rawMessage.toLowerCase();

    if (
      error?.status === 429 ||
      lowered.includes("429") ||
      lowered.includes("rate limit") ||
      lowered.includes("resource has been exhausted")
    ) {
      return {
        toast: "Rate limit reached. Please wait a bit and try again.",
        title: "Rate limit reached",
        detail: "The AI service is temporarily rate-limited. Try again in a minute.",
        type: "warning",
      };
    }

    if (
      lowered.includes("transcript button not found") ||
      lowered.includes("no transcript available") ||
      lowered.includes("no transcript segments")
    ) {
      return {
        toast: "Transcript not available for this video.",
        title: "Transcript not found",
        detail: "Try enabling captions or open a video with transcripts available.",
        type: "error",
      };
    }

    if (lowered.includes("failed to fetch") || lowered.includes("network")) {
      return {
        toast: "Network error while generating notes.",
        title: "Network error",
        detail: "Check your connection and try again.",
        type: "error",
      };
    }

    return {
      toast: rawMessage || "Failed to generate notes.",
      title: "Could not generate notes",
      detail: rawMessage || "Please try again.",
      type: "error",
    };
  }

  function showTranscriptPreview(transcript) {
    const tokens = estimateTokens(transcript);
    const cost = estimateCost(tokens);
    const hints = [];

    if (state.videoDuration && state.videoDuration > 7200) {
      hints.push("Long video detected. Generation may take 30-45s.");
    }
    if (state.transcriptQuality < 0.7) {
      hints.push("Auto-generated captions detected. Notes quality may vary.");
    }
    if (state.hasChapters) {
      hints.push("Chapters available. Enable “Include chapters” for markers.");
    }

    panelElements.transcriptPreview.style.display = "block";
    panelElements.transcriptPreview.innerHTML = `
      <div class="ytn-transcript-preview ytn-fade-in">
        <div class="ytn-transcript-header">
          <div class="ytn-transcript-label">Transcript Detected</div>
          <div class="ytn-transcript-stats">${tokens.toLocaleString()} tokens</div>
        </div>
        <div class="ytn-transcript-content">
          ${transcript.substring(0, 200)}...
        </div>
        ${
          hints.length
            ? `<div class="ytn-transcript-hints">
                ${hints
                  .map(
                    (hint) => `<div class="ytn-transcript-hint">${hint}</div>`
                  )
                  .join("")}
              </div>`
            : ""
        }
      </div>
    `;

    // Show cost estimate
    panelElements.costEstimate.style.display = "block";
    panelElements.costEstimate.innerHTML = `Estimated cost: <strong>$${cost}</strong> • ~10-15 seconds`;
  }

  async function promptForApiKey() {
    return new Promise((resolve) => {
      const apiKey = prompt(
        "Enter your Google Gemini API Key:\n\nGet your free API key at: https://aistudio.google.com/app/apikey"
      );
      resolve(apiKey?.trim() || null);
    });
  }

  function handleCopy() {
    const notes = getNotesForDepth(state.activeDepth);
    if (!notes) return;

    navigator.clipboard
      .writeText(notes)
      .then(() => {
        showToast("Notes copied to clipboard!", "success");
      })
      .catch(() => {
        showToast("Failed to copy notes", "error");
      });
  }

  function handleDownload() {
    const notes = getNotesForDepth(state.activeDepth);
    if (!notes) return;

    const blob = new Blob([notes], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${state.currentVideoTitle || "youtube-notes"}-${
      state.activeDepth
    }.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    showToast("Notes downloaded!", "success");
  }

  function handleEdit() {
    const notes = getNotesForDepth(state.activeDepth);
    if (!notes) return;

    if (state.isEditing) {
      // Save edit
      saveEdit();
    } else {
      // Enter edit mode
      state.isEditing = true;
      panelElements.notesEditor.value = notes;
      panelElements.notesContent.style.display = "none";
      panelElements.notesEditor.style.display = "block";
      panelElements.editBtn.innerHTML = `
        <svg viewBox="0 0 24 24" fill="currentColor">
          <path d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z"/>
        </svg>
        Save
      `;
      panelElements.editBtn.classList.add("ytn-btn-primary");
      panelElements.editBtn.classList.remove("ytn-btn-secondary");
      panelElements.notesEditor.focus();
    }
  }

  async function saveEdit() {
    const editedNotes = panelElements.notesEditor.value;
    state.notesByDepth[state.activeDepth] = editedNotes;

    // Save to storage
    await saveNotes(state.currentVideoId);

    // Exit edit mode
    state.isEditing = false;
    panelElements.notesContent.style.display = "block";
    panelElements.notesEditor.style.display = "none";
    panelElements.editBtn.innerHTML = `
      <svg viewBox="0 0 24 24" fill="currentColor">
        <path d="M20.71,7.04C21.1,6.65 21.1,6 20.71,5.63L18.37,3.29C18,2.9 17.35,2.9 16.96,3.29L15.12,5.12L18.87,8.87M3,17.25V21H6.75L17.81,9.93L14.06,6.18L3,17.25Z"/>
      </svg>
      Edit
    `;
    panelElements.editBtn.classList.remove("ytn-btn-primary");
    panelElements.editBtn.classList.add("ytn-btn-secondary");

    // Update display
    displayNotesForDepth(state.activeDepth);
    showToast("Notes saved!", "success");
  }

  function cancelEdit() {
    state.isEditing = false;
    panelElements.notesContent.style.display = "block";
    panelElements.notesEditor.style.display = "none";
    panelElements.editBtn.innerHTML = `
      <svg viewBox="0 0 24 24" fill="currentColor">
        <path d="M20.71,7.04C21.1,6.65 21.1,6 20.71,5.63L18.37,3.29C18,2.9 17.35,2.9 16.96,3.29L15.12,5.12L18.87,8.87M3,17.25V21H6.75L17.81,9.93L14.06,6.18L3,17.25Z"/>
      </svg>
      Edit
    `;
    panelElements.editBtn.classList.remove("ytn-btn-primary");
    panelElements.editBtn.classList.add("ytn-btn-secondary");
    showToast("Edit cancelled", "info", 2000);
  }

  // ==================== UI DISPLAY ====================

  function displayNotesForDepth(depth) {
    state.activeDepth = depth;
    const notes = getNotesForDepth(depth);
    panelElements.notesContent.style.display = "block";

    if (!notes) {
      panelElements.notesContent.innerHTML =
        "<p>No notes for this depth yet. Click Generate Notes to create them.</p>";
    } else {
      const html = renderMarkdown(notes);
      panelElements.notesContent.innerHTML = html;
    }

    // Hide empty state and progress
    panelElements.contentArea.style.display = "none";
    panelElements.progressArea.style.display = "none";
    panelElements.costEstimate.style.display = "none";

    // Show action buttons
    panelElements.actionsSecondary.style.display = "flex";
    const hasNotes = Boolean(notes);
    panelElements.copyBtn.style.display = hasNotes ? "inline-flex" : "none";
    panelElements.downloadBtn.style.display = hasNotes ? "inline-flex" : "none";
    panelElements.editBtn.style.display = hasNotes ? "inline-flex" : "none";
    panelElements.regenerateBtn.style.display = "inline-flex";
  }

  function renderMarkdown(text) {
    const normalized = text
      .replace(
        /^\s*-\s+\*\*(Executive Summary|Key Themes|Critical Insights|Notable Quotes|Recommendations)\*\*\s*:?/gim,
        "## $1"
      )
      .replace(/^\s*-\s+(#{2,3})\s+/gm, "$1 ")
      .replace(/^\s*\*\s+/gm, "- ");

    const escapeHtml = (input) =>
      input.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

    const formatInline = (input) => {
      const escaped = escapeHtml(input);
      const parts = escaped.split(/`/);
      return parts
        .map((part, index) => {
          if (index % 2 === 1) {
            return `<code>${part}</code>`;
          }
          return part
            .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
            .replace(/\*(.+?)\*/g, "<em>$1</em>");
        })
        .join("");
    };

    const lines = normalized.split(/\r?\n/);
    const html = [];
    const listStack = [];
    let paragraphBuffer = [];

    const closeParagraph = () => {
      if (paragraphBuffer.length) {
        html.push(`<p>${formatInline(paragraphBuffer.join(" "))}</p>`);
        paragraphBuffer = [];
      }
    };

    const closeLists = (targetLevel = 0) => {
      while (listStack.length > targetLevel) {
        const list = listStack.pop();
        html.push(`</${list.type}>`);
      }
    };

    const openList = (type) => {
      html.push(`<${type}>`);
      listStack.push({ type });
    };

    const parseTable = (startIndex) => {
      const headerLine = lines[startIndex];
      const separatorLine = lines[startIndex + 1];
      if (!separatorLine) return null;
      const separatorPattern = /^\s*\|?(\s*:?-+:?\s*\|)+\s*:?-+:?\s*\|?\s*$/;
      if (!separatorPattern.test(separatorLine)) return null;

      const parseRow = (row) =>
        row
          .trim()
          .replace(/^\|/, "")
          .replace(/\|$/, "")
          .split("|")
          .map((cell) => formatInline(cell.trim()));

      const headerCells = parseRow(headerLine);
      let i = startIndex + 2;
      const bodyRows = [];
      while (i < lines.length && /\|/.test(lines[i])) {
        bodyRows.push(parseRow(lines[i]));
        i += 1;
      }

      let tableHtml = "<table><thead><tr>";
      tableHtml += headerCells.map((cell) => `<th>${cell}</th>`).join("");
      tableHtml += "</tr></thead><tbody>";
      tableHtml += bodyRows
        .map(
          (row) => `<tr>${row.map((cell) => `<td>${cell}</td>`).join("")}</tr>`
        )
        .join("");
      tableHtml += "</tbody></table>";
      return { html: tableHtml, nextIndex: i };
    };

    let i = 0;
    while (i < lines.length) {
      const line = lines[i];
      const trimmed = line.trim();

      if (!trimmed) {
        closeParagraph();
        closeLists(0);
        i += 1;
        continue;
      }

      const tableResult = parseTable(i);
      if (tableResult) {
        closeParagraph();
        closeLists(0);
        html.push(tableResult.html);
        i = tableResult.nextIndex;
        continue;
      }

      const headingMatch = trimmed.match(/^(#{1,3})\s+(.*)$/);
      if (headingMatch) {
        closeParagraph();
        closeLists(0);
        const level = headingMatch[1].length;
        html.push(`<h${level}>${formatInline(headingMatch[2])}</h${level}>`);
        i += 1;
        continue;
      }

      if (trimmed.startsWith(">")) {
        closeParagraph();
        closeLists(0);
        const quoteLines = [];
        while (i < lines.length && lines[i].trim().startsWith(">")) {
          quoteLines.push(lines[i].replace(/^\s*>\s?/, ""));
          i += 1;
        }
        const quoteContent = quoteLines
          .map((q) => formatInline(q))
          .join("<br>");
        html.push(`<blockquote>${quoteContent}</blockquote>`);
        continue;
      }

      const listMatch = line.match(/^(\s*)([-*]|\d+\.)\s+(.*)$/);
      if (listMatch) {
        closeParagraph();
        const indent = listMatch[1].replace(/\t/g, "  ").length;
        const level = Math.floor(indent / 2);
        const isOrdered = /^\d+\./.test(listMatch[2]);
        const listType = isOrdered ? "ol" : "ul";

        if (listStack.length < level + 1) {
          while (listStack.length < level) {
            openList("ul");
          }
          openList(listType);
        } else if (listStack.length > level + 1) {
          closeLists(level + 1);
        }

        const current = listStack[listStack.length - 1];
        if (current && current.type !== listType) {
          closeLists(level);
          openList(listType);
        }

        html.push(`<li>${formatInline(listMatch[3])}</li>`);
        i += 1;
        continue;
      }

      paragraphBuffer.push(trimmed);
      i += 1;
    }

    closeParagraph();
    closeLists(0);
    return html.join("\n");
  }

  function updateGenerateButton(isLoading) {
    const btn = panelElements.generateBtn;
    if (isLoading) {
      btn.disabled = true;
      btn.innerHTML = `
        <div class="ytn-spinner"></div>
        Generating...
      `;
    } else {
      btn.disabled = false;
      btn.innerHTML = "Generate Notes";
    }
  }

  function togglePanel(show = null) {
    const panel = document.getElementById(CONFIG.PANEL_ID);
    if (!panel) return;

    if (show === null) {
      // Toggle
      const isVisible = !panel.classList.contains("ytn-hidden");
      panel.classList.toggle("ytn-hidden", isVisible);
    } else {
      panel.classList.toggle("ytn-hidden", !show);
    }
  }

  async function openNotesLibrary() {
    // Ensure storage is synced before opening library
    // Small delay to ensure Chrome storage has fully persisted
    await new Promise((resolve) => setTimeout(resolve, 100));

    // Open notes library in new tab
    const libraryUrl = chrome.runtime.getURL("notes-library.html");
    window.open(libraryUrl, "_blank");
  }

  // ==================== INITIALIZATION ====================

  async function init() {
    console.log("[YouTube Notes] Initializing extension");

    // Wait for page to load
    if (document.readyState === "loading") {
      document.addEventListener("DOMContentLoaded", init);
      return;
    }

    // Check if we're on a watch page
    if (!window.location.pathname.includes("/watch")) {
      return;
    }

    // Extract video ID
    const urlParams = new URLSearchParams(window.location.search);
    const videoId = urlParams.get("v");

    if (!videoId) {
      return;
    }

    state.currentVideoId = videoId;
    state.currentVideoUrl = window.location.href;
    state.currentVideoTitle = document.title.replace(" - YouTube", "");

    await loadUserSettings();

    state.videoDuration = getVideoDurationSeconds();
    state.chapters = detectChapters();
    state.hasChapters = state.chapters.length > 0;
    const captionInfo = getCaptionTrackInfo();
    if (captionInfo) {
      state.transcriptQuality = captionInfo.isAutoGenerated ? 0.6 : 0.9;
    }

    // Load panel state
    await loadPanelState();

    // Create panel
    createPanel();

    // Create toolbar button
    createToolbarButton();

    // Start with panel visible
    togglePanel(true);

    const hasSavedNotes = await loadSavedNotes();
    if (!hasSavedNotes) {
      scheduleAutoGenerateIfEligible();
    }

    // Initialize keyboard shortcuts
    initKeyboardShortcuts();

    console.log("[YouTube Notes] Extension initialized for video:", videoId);
  }

  // Start initialization
  init();
})();
